version: "2.0"
services:
  fastapi:
    image: kde6260/bookk-bookk:$BOOKK_BOOKK_VERSION
    networks:
      book_net:
        ipv4_address: 172.16.238.3
    ports:
      - 8000:8000
    volumes:
      - /home/ubuntu/bookk-bookk/.env:/home/bookk-bookk/.env

  nginx:
    image: nginx:1.18.0
    network_mode: "host"
    ports:
      - 443:443
    volumes:
      - /home/ubuntu/bookk-bookk-infra/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/lovelace-book.dev-daeun.com/fullchain.pem:/etc/ssl_keys/fullchain.pem
      - /etc/letsencrypt/live/lovelace-book.dev-daeun.com/privkey.pem:/etc/ssl_keys/privkey.pem
      - /etc/letsencrypt/live/lovelace-book.dev-daeun.com/chain.pem:/etc/ssl_keys/chain.pem
      - /etc/dhparam.pem:/etc/ssl_keys/dhparam.pem
networks:
  book_net:
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
